Repository naruhiyo/partytion, pull requests merged in 2019-08, with the labels that each got.

#22 XCodeが起動できないエラーを修正
  .gitignore
  README.md
  partytion-app/Cartfile
  partytion-app/Cartfile.resolved
  partytion-app/Partytion-Bridging-Header.h
  partytion-app/PartytionApp.xcodeproj/project.pbxproj
  partytion-app/PartytionApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  partytion-app/PartytionApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  partytion-app/PartytionApp.xcodeproj/project.xcworkspace/xcuserdata/tatsuya.xcuserdatad/UserInterfaceState.xcuserstate
  partytion-app/PartytionApp.xcodeproj/xcuserdata/tatsuya.xcuserdatad/xcschemes/xcschememanagement.plist
  partytion-app/PartytionApp/AppDelegate.swift
  partytion-app/PartytionApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  partytion-app/PartytionApp/Assets.xcassets/Contents.json
  partytion-app/PartytionApp/Base.lproj/LaunchScreen.storyboard
  partytion-app/PartytionApp/Info.plist
  partytion-app/PartytionApp/Presentation/View/Base.lproj/Main.storyboard
  partytion-app/PartytionApp/Presentation/View/SplashScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/SplashViewController.swift
  partytion-app/PartytionApp/Presentation/View/ViewController.swift
  partytion-app/PartytionApp/assets/BeerBubbles.json
  partytion-app/PartytionAppTests/Info.plist
  partytion-app/PartytionAppTests/partytion_appTests.swift
  partytion-app/PartytionAppUITests/Info.plist
  partytion-app/PartytionAppUITests/partytion_appUITests.swift
Labels: bug, enhancement

#24 スプラッシュスクリーンの追加
  partytion-app/PartytionApp.xcodeproj/project.pbxproj
  partytion-app/PartytionApp.xcodeproj/project.xcworkspace/xcuserdata/tatsuya.xcuserdatad/UserInterfaceState.xcuserstate
  partytion-app/PartytionApp/Presentation/View/Base.lproj/MainScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/MainViewController.swift
  partytion-app/PartytionApp/Presentation/View/SplashScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/SplashViewController.swift
Labels: enhancement

#25 質問入力画面の追加
  partytion-app/PartytionApp.xcodeproj/project.pbxproj
  partytion-app/PartytionApp.xcodeproj/project.xcworkspace/xcuserdata/tatsuya.xcuserdatad/UserInterfaceState.xcuserstate
  partytion-app/PartytionApp/Presentation/View/Base.lproj/MainScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/MainViewController.swift
  partytion-app/PartytionApp/Presentation/View/QuestionScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/QuestionViewController.swift
  partytion-app/PartytionApp/Presentation/View/SplashScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/SplashViewController.swift
Labels: enhancement

#29 結果画面の追加
  partytion-app/Cartfile
  partytion-app/Cartfile.resolved
  partytion-app/PartytionApp.xcodeproj/project.pbxproj
  partytion-app/PartytionApp/Presentation/View/Base.lproj/MainScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/MainViewController.swift
  partytion-app/PartytionApp/Presentation/View/ResultScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/ResultViewController.swift
Labels: enhancement

#28 プレイヤー数入力画面の追加
  partytion-app/PartytionApp.xcodeproj/project.pbxproj
  partytion-app/PartytionApp.xcodeproj/project.xcworkspace/xcuserdata/tatsuya.xcuserdatad/UserInterfaceState.xcuserstate
  partytion-app/PartytionApp/Presentation/View/Base.lproj/MainScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/HowToScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/HowToViewController.swift
  partytion-app/PartytionApp/Presentation/View/PlayerScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/PlayerViewController.swift
  partytion-app/PartytionApp/Presentation/View/QuestionViewController.swift
  partytion-app/PartytionApp/Presentation/View/SplashViewController.swift
Labels: enhancement

#27 HowTo画面の追加
  partytion-app/PartytionApp.xcodeproj/project.pbxproj
  partytion-app/PartytionApp/Presentation/View/Base.lproj/MainScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/HowToScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/HowToViewController.swift
  partytion-app/PartytionApp/Presentation/View/PlayerScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/PlayerViewController.swift
  partytion-app/PartytionApp/Presentation/View/SplashViewController.swift
Labels: enhancement

#30 全Viewへの紐付け
  .gitignore
  Documentations/Requirements.md
  Documentations/StateChangeDiagram.puml
  Documentations/Wireframe/PartytionMock.drawio
  README.md
  partytion-app/Cartfile
  partytion-app/Cartfile.resolved
  partytion-app/Partytion-Bridging-Header.h
  partytion-app/PartytionApp.xcodeproj/project.pbxproj
  partytion-app/PartytionApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  partytion-app/PartytionApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  partytion-app/PartytionApp/AppDelegate.swift
  partytion-app/PartytionApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  partytion-app/PartytionApp/Assets.xcassets/Contents.json
  partytion-app/PartytionApp/Base.lproj/LaunchScreen.storyboard
  partytion-app/PartytionApp/Info.plist
  partytion-app/PartytionApp/Presentation/View/AnswerScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/AnswerViewController.swift
  partytion-app/PartytionApp/Presentation/View/HowToScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/HowToViewController.swift
  partytion-app/PartytionApp/Presentation/View/PlayerScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/PlayerViewController.swift
  partytion-app/PartytionApp/Presentation/View/QuestionScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/QuestionViewController.swift
  partytion-app/PartytionApp/Presentation/View/ResultScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/ResultViewController.swift
  partytion-app/PartytionApp/Presentation/View/SplashScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/SplashViewController.swift
  partytion-app/PartytionApp/assets/BeerBubbles.json
  partytion-app/PartytionAppTests/Info.plist
  partytion-app/PartytionAppTests/partytion_appTests.swift
  partytion-app/PartytionAppUITests/Info.plist
  partytion-app/PartytionAppUITests/partytion_appUITests.swift
Labels: enhancement

#36 Get result value from answer view
  partytion-app/PartytionApp/Presentation/View/AnswerViewController.swift
  partytion-app/PartytionApp/Presentation/View/ResultViewController.swift
Labels: enhancement

#38 各画面のビジネスロジック
  partytion-app/PartytionApp.xcodeproj/project.pbxproj
  partytion-app/PartytionApp/AppDelegate.swift
  partytion-app/PartytionApp/Entity/PartytionDB.xcdatamodeld/PartytionDB.xcdatamodel/contents
  partytion-app/PartytionApp/PartytionApp.entitlements
  partytion-app/PartytionApp/Presentation/Presenter/AnswerPresenter.swift
  partytion-app/PartytionApp/Presentation/Presenter/BasePresenter.swift
  partytion-app/PartytionApp/Presentation/Presenter/QuestionPresenter.swift
  partytion-app/PartytionApp/Presentation/Presenter/ResultPresenter.swift
  partytion-app/PartytionApp/Presentation/View/AnswerScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/AnswerViewController.swift
  partytion-app/PartytionApp/Presentation/View/PlayerViewController.swift
  partytion-app/PartytionApp/Presentation/View/QuestionScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/QuestionViewController.swift
  partytion-app/PartytionApp/Presentation/View/ResultScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/ResultViewController.swift
  partytion-app/PartytionApp/Utils/DateFormatter.swift
Labels: enhancement, refactoring
