Repository naruhiyo/partytion, pull requests merged in 2019-10, with the labels that each got.

#43 Feature/refactoring
  .gitignore
  README.md
  partytion-app/Cartfile.resolved
  partytion-app/PartytionApp.xcodeproj/project.pbxproj
  partytion-app/PartytionApp.xcworkspace/contents.xcworkspacedata
  partytion-app/PartytionApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  partytion-app/PartytionApp/Entity/Components/FileIO.swift
  partytion-app/PartytionApp/Entity/Components/JSONParser.swift
  partytion-app/PartytionApp/Entity/Components/QuestionThemeJSONParser.swift
  partytion-app/PartytionApp/Entity/PartytionDB.xcdatamodeld/PartytionDB.xcdatamodel/contents
  partytion-app/PartytionApp/Entity/QuestionThemeEntity.swift
  partytion-app/PartytionApp/Presentation/Components/CustomUIColor.swift
  partytion-app/PartytionApp/Presentation/Components/PlaceHolderTextView.swift
  partytion-app/PartytionApp/Presentation/Presenter/AnswerPresenter.swift
  partytion-app/PartytionApp/Presentation/Presenter/HowToPresenter.swift
  partytion-app/PartytionApp/Presentation/Presenter/PlayerPresenter.swift
  partytion-app/PartytionApp/Presentation/Presenter/QuestionPresenter.swift
  partytion-app/PartytionApp/Presentation/Presenter/ResultPresenter.swift
  partytion-app/PartytionApp/Presentation/Presenter/SplashPresenter.swift
  partytion-app/PartytionApp/Presentation/View/AnswerScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/AnswerViewController.swift
  partytion-app/PartytionApp/Presentation/View/HowToScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/HowToViewController.swift
  partytion-app/PartytionApp/Presentation/View/PlayerScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/PlayerViewController.swift
  partytion-app/PartytionApp/Presentation/View/QuestionScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/QuestionViewController.swift
  partytion-app/PartytionApp/Presentation/View/ResultScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/ResultViewController.swift
  partytion-app/PartytionApp/Presentation/View/SplashScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/SplashViewController.swift
  partytion-app/PartytionApp/Utils/DateFormatter.swift
  partytion-app/PartytionApp/assets/BeerBubbles.json
  partytion-app/PartytionApp/assets/Oshidashi-M-Gothic.otf
  partytion-app/PartytionApp/assets/SeedData.json
  partytion-app/Podfile
  partytion-app/Podfile.lock
Labels: task

#46 Feature/document
  LICENSE
  README.md
  partytion-app/PartytionApp/Presentation/View/HowToScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/HowToViewController.swift
Labels: documentation

#47 Feature/keyboard
  partytion-app/PartytionApp/Presentation/View/QuestionViewController.swift
Labels: enhancement

#49 Add animation in screen transition
  partytion-app/PartytionApp/Entity/PartytionDB.xcdatamodeld/PartytionDB.xcdatamodel/contents
  partytion-app/PartytionApp/Presentation/Presenter/QuestionPresenter.swift
  partytion-app/PartytionApp/Presentation/View/QuestionScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/ResultScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/ResultViewController.swift
  partytion-app/PartytionApp/Presentation/View/RootViewWireframe.swift
Labels: enhancement

#52 Feature/hiyoko3/enhancement
  partytion-app/PartytionApp.xcodeproj/project.pbxproj
  partytion-app/PartytionApp/Presentation/Presenter/HowToPresenter.swift
  partytion-app/PartytionApp/Presentation/View/Controllers/AnswerViewController.swift
  partytion-app/PartytionApp/Presentation/View/Controllers/HowToViewController.swift
  partytion-app/PartytionApp/Presentation/View/Controllers/PlayerViewController.swift
  partytion-app/PartytionApp/Presentation/View/Controllers/QuestionViewController.swift
  partytion-app/PartytionApp/Presentation/View/Controllers/ResultViewController.swift
  partytion-app/PartytionApp/Presentation/View/Controllers/SplashViewController.swift
  partytion-app/PartytionApp/Presentation/View/HowToScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/HowToViewController.swift
  partytion-app/PartytionApp/Presentation/View/Storyboards/AnswerScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/Storyboards/HowToScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/Storyboards/PlayerScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/Storyboards/QuestionScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/Storyboards/ResultScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/Storyboards/RootScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/Storyboards/SplashScreen.storyboard
  partytion-app/PartytionApp/Presentation/View/WireFrame/RootViewController.swift
  partytion-app/PartytionApp/Presentation/View/WireFrame/RootViewWireframe.swift
  partytion-app/PartytionApp/assets/sample.gif
  partytion-app/Podfile
  partytion-app/Podfile.lock
Labels: refactoring, task
